#ifndef ARDUINO
#include"PlayerOwnedGames.h"
#include"Player.h"
#include"Compatible.h"
#endif


#ifdef WINDOWS_SYSTEM
#pragma warning(disable:4996)
#include<conio.h>
#include<iostream>
using std::cout;
#endif

CP_GLOBALSTATE char sg_cMap[7][16][32] =
{
	{
		{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
		BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, BOX, PATH, BOX, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, PERSON, BOX, PATH, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, BOX, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
	},
	//CP_GLOBALSTATE char sg_cMap2[16][32] =
{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, PERSON, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, PATH, BOX, BOX, OBSTACLE, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, PATH, BOX, PATH, OBSTACLE, BLANK, OBSTACLE, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, PATH, OBSTACLE, OBSTACLE, OBSTACLE, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, PATH, PATH, PATH, PATH, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, PATH, PATH, OBSTACLE, PATH, PATH, OBSTACLE, BLANK,BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, PATH, PATH, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
},
//CP_GLOBALSTATE char sg_cMap3[16][32] =
{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, PATH, PATH, PATH, PATH, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, BOX, OBSTACLE, OBSTACLE, OBSTACLE, PATH, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, PATH, PERSON, PATH, BOX, PATH, PATH, BOX, PATH, OBSTACLE, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, PATH, AIM, AIM, OBSTACLE, PATH, BOX, PATH, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, AIM, AIM, OBSTACLE, PATH, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
},
//CP_GLOBALSTATE char sg_cMap4[16][32] =
{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, PERSON, BOX, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, BOX, PATH, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, PATH, BOX, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, BOX, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, AIM, BOX_AIM, AIM, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
},
//CP_GLOBALSTATE char sg_cMap5[16][32] =
{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, PERSON, PATH, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, BOX, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, PATH, OBSTACLE, PATH, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, OBSTACLE, PATH, OBSTACLE, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, BOX, PATH, PATH, OBSTACLE, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, AIM, PATH, PATH, PATH, BOX, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
},
//CP_GLOBALSTATE char sg_cMap6[16][32] =
{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, PATH, PATH, PATH, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, PATH, PATH, PATH, AIM, OBSTACLE, OBSTACLE, OBSTACLE, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, PATH, OBSTACLE, PATH, OBSTACLE, PATH, PATH, PATH, PATH, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, PATH, OBSTACLE, PATH, BOX, PATH, BOX, OBSTACLE, AIM, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, PATH, OBSTACLE, PATH, PATH, BOX_AIM, PATH, PATH, OBSTACLE, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, PATH, AIM, OBSTACLE, BOX, PATH, BOX, PATH, OBSTACLE, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, OBSTACLE, OBSTACLE, PATH, PATH, PATH, PATH, OBSTACLE, PATH, OBSTACLE, PATH, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, PATH, OBSTACLE, OBSTACLE, OBSTACLE, AIM, PATH, PATH, PATH, PATH, PERSON, OBSTACLE, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, PATH, PATH, PATH, PATH, PATH, OBSTACLE, OBSTACLE, PATH, PATH, PATH, OBSTACLE, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK ,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
},

{
	{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
	BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, OBSTACLE, PATH, PATH, OBSTACLE, PATH, PERSON, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, PATH, PATH, OBSTACLE, BOX, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, BOX, PATH, PATH, BOX, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, OBSTACLE, PATH, BOX, OBSTACLE, OBSTACLE, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, PATH, BOX, PATH, OBSTACLE, PATH, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, AIM, AIM, AIM, AIM, AIM, PATH, PATH, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK },
{ BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK }
}
};

CSokoban* CSokoban::Instance()
{
	static CSokoban Instance;
	return &Instance;

}

CSokoban::CSokoban()
{

}

void CSokoban::Enter(CPlayer*player)
{
	CLS;
	level = 0;
	memset(m_ggiPrintSave, BLANK, sizeof(m_ggiPrint));
	memcpy(m_ggiPrint, CP_GLOBAL(sg_cMap[level]), sizeof(m_ggiPrint));
	person = CPosition(7, 8);

}


void CSokoban::Execute(CPlayer*player)
{
	auto start = CP_CLOCK;
	auto finish = start + REFRESHTIME;
	keyin tem = NOOPERATION;
	while (CP_CLOCK < finish && !(tem = PressKey()))
	{

	}
	if (tem)
		switch (tem)
		{
		case UP:
		case DOWN:
		case LEFT:
		case RIGHT:
		case UP2:
		case DOWN2:
		case LEFT2:
		case RIGHT2:
			Move(tem);
			break;
		case EXIT:
			player->ChangeState(NONE);
			break;
		case NEXT:
			SetMap(++level);
			break;
		case BACK:
			SetMap(--level);
			break;
		case RESTART:
		case RESET:
			SetMap(level);
			break;

		}



	Print(SOKOBAN, m_ggiPrint, m_ggiPrintSave);
	memcpy(m_ggiPrintSave, m_ggiPrint, sizeof(m_ggiPrint));

	if (win())
	{
		SetMap(++level);
	}

	int RefreshTime = finish - CP_CLOCK;
	if (RefreshTime < 1)
		RefreshTime = 1;
	CP_SLEEP(RefreshTime);
}

void CSokoban::Exit(CPlayer*player)
{

}
bool CSokoban::win()
{
	for (int i = 0; i < 16; i++)
	{
		for (int j = 0; j < 16; j++)
		{
			if (m_ggiPrint[i][j] == AIM || m_ggiPrint[i][j] == PERSON_AIM)
			{
				return 0;
			}
		}
	}
	return 1;
}

void CSokoban::SetMap(unsigned char& level)
{
	CP_SLEEP(200);
	CLS;
	switch (level)
	{
	case 255:
		person = CPosition(10, 5);
		level = 6;
		break;
	case 0:
		person = CPosition(7, 8);
		break;
	case 1:
		person = CPosition(4, 4);
		break;
	case 2:
		person = CPosition(5, 7);
		break;
	case 3:
		person = CPosition(6, 5);
		break;
	case 4:
		person = CPosition(6, 5);
		break;
	case 5:
		person = CPosition(12, 10);
		break;
	case 6:
		person = CPosition(10, 5);
		break;
	case 7:
		person = CPosition(7, 8);
		level = 0;
		break;
	}
	memset(m_ggiPrintSave, BLANK, sizeof(m_ggiPrint));
	memcpy(m_ggiPrint, CP_GLOBAL(sg_cMap[level]), sizeof(m_ggiPrint));
	Print(SOKOBAN, m_ggiPrint, m_ggiPrintSave);
	memcpy(m_ggiPrintSave, m_ggiPrint, sizeof(m_ggiPrint));
	CP_SLEEP(100);
}

void CSokoban::Move(keyin &dir)
{
	person.Move(dir, next);
	next.Move(dir, next2);
	if (m_ggiPrint[next.Get_Y()][next.Get_X()] == PATH)
	{
		m_ggiPrint[person.Get_Y()][person.Get_X()] -= 2;   //from person(2) to blank(0)
		m_ggiPrint[next.Get_Y()][next.Get_X()] += 2;       //form blank(0) to person(2)
		person.Move(dir);
	}
	else if (m_ggiPrint[next.Get_Y()][next.Get_X()] == BOX)
	{
		if (m_ggiPrint[next2.Get_Y()][next2.Get_X()] == PATH || m_ggiPrint[next2.Get_Y()][next2.Get_X()] == AIM)
		{
			m_ggiPrint[person.Get_Y()][person.Get_X()] -= 2;
			m_ggiPrint[next.Get_Y()][next.Get_X()] = PERSON;
			m_ggiPrint[next2.Get_Y()][next2.Get_X()] += 3;
			person.Move(dir);
		}
	}
	else if (m_ggiPrint[next.Get_Y()][next.Get_X()] == AIM)
	{
		m_ggiPrint[person.Get_Y()][person.Get_X()] -= 2;
		m_ggiPrint[next.Get_Y()][next.Get_X()] = PERSON_AIM;
		person.Move(dir);
	}
	else if (m_ggiPrint[next.Get_Y()][next.Get_X()] == BOX_AIM)
	{
		if (m_ggiPrint[next2.Get_Y()][next2.Get_X()] == PATH || m_ggiPrint[next2.Get_Y()][next2.Get_X()] == AIM)
		{
			m_ggiPrint[person.Get_Y()][person.Get_X()] -= 2;
			m_ggiPrint[next.Get_Y()][next.Get_X()] = PERSON_AIM;
			m_ggiPrint[next2.Get_Y()][next2.Get_X()] += 3;
			person.Move(dir);
		}
	}
}